# Use Python 3.9 base image
FROM python:3.11

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-dev \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy only requirements first for better caching
COPY requirements.txt .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY privacy_enhanced_prizes/ /app/

# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
# CMD ["python", "-m", "server.main"]
CMD ["uvicorn", "server.main:app", "--host", "0.0.0.0", "--port", "443", "--log-level", "warning", "--ssl-keyfile=key.pem", "--ssl-certfile=cert.pem"]